// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Modal': string;
  'Modal__buttons': string;
  'Modal__content': string;
  'Modal__title': string;
  'Modal__title_warning': string;
}
declare const cssExports: CssExports;
export = cssExports;
