// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'iconButton': string;
  'iconButton_delete': string;
  'iconButton_edit': string;
  'iconButton_warning': string;
}
declare const cssExports: CssExports;
export = cssExports;
