// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'SelectorItemsPerPage': string;
  'SelectorItemsPerPage__selector': string;
  'TableToolbar': string;
}
declare const cssExports: CssExports;
export = cssExports;
