// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Table': string;
  'Table__actionColumn': string;
}
declare const cssExports: CssExports;
export = cssExports;
