// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'TableManager': string;
  'TableManager__table': string;
  'TableManager__toolbar': string;
  'button': string;
  'buttonGroup': string;
  'buttonGroup__button': string;
  'buttonGroup__button_active': string;
  'button_active': string;
}
declare const cssExports: CssExports;
export = cssExports;
