// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Paginator': string;
  'Paginator__container': string;
  'Paginator__item': string;
  'Paginator__link': string;
  'Paginator__link_active': string;
}
declare const cssExports: CssExports;
export = cssExports;
