// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'StatisticItem': string;
  'StatisticItem__container': string;
  'StatisticItem__description': string;
  'StatisticItem__line': string;
  'StatisticItem__measure': string;
}
declare const cssExports: CssExports;
export = cssExports;
