// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'New': string;
  'New__date': string;
  'New__description': string;
  'New__img': string;
  'New__imgContainer': string;
  'New__title': string;
}
declare const cssExports: CssExports;
export = cssExports;
