// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'News': string;
  'News__bg': string;
  'News__container': string;
}
declare const cssExports: CssExports;
export = cssExports;
