// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Feedback': string;
  'Feedback__text': string;
  'Feedback__title': string;
  'Feedbacks': string;
  'Feedbacks__title': string;
}
declare const cssExports: CssExports;
export = cssExports;
