// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Button': string;
  'Button_warning': string;
}
declare const cssExports: CssExports;
export = cssExports;
