// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Contacts': string;
  'Contacts__icon': string;
  'Contacts__item': string;
  'Contacts__items': string;
  'Contacts__label': string;
  'Header': string;
  'Header__contact': string;
  'Header__container': string;
  'Header__hiddenContent': string;
  'Header__logo': string;
  'Header__navigation': string;
  'Header__toggler': string;
  'Header_open': string;
  'Logo': string;
  'Navigation': string;
  'Navigation__item': string;
  'Navigation__link': string;
  'Toggler': string;
}
declare const cssExports: CssExports;
export = cssExports;
