// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'AboutCompany': string;
  'AboutCompany__left': string;
}
declare const cssExports: CssExports;
export = cssExports;
