// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Contacts': string;
  'ContactsForm': string;
  'ContactsForm__btn': string;
  'ContactsForm__input': string;
  'ContactsForm__title': string;
  'ContactsGroup': string;
  'ContactsGroup__item': string;
  'ContactsGroup__title': string;
  'ContactsInfo': string;
  'ContactsInfo__container': string;
  'ContactsInfo__content': string;
  'ContactsInfo__title': string;
}
declare const cssExports: CssExports;
export = cssExports;
