// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Patchcord': string;
  'Slide': string;
  'Slide__line': string;
  'Slide__text': string;
  'Slide__textContainer': string;
  'Slider': string;
  'Slider__button': string;
  'Slider__container': string;
  'Slider__next': string;
  'Slider__prev': string;
}
declare const cssExports: CssExports;
export = cssExports;
